import { normalizeText } from '@/modules/catalog/normalize';

export type CrateContinent =
  | 'africa'
  | 'asia'
  | 'europe'
  | 'northAmerica'
  | 'southAmerica'
  | 'oceania'
  | 'antarctica'
  | 'international'
  | 'unknown';

/**
 * Geography of country names. The caller supplies documented artist origins for crates;
 * this conversion does not infer an artist's origin from a release territory.
 * Country assignments follow UN M49 (consulted 2026-09-18):
 * https://unstats.un.org/unsd/methodology/m49/
 * North America combines Northern America, Central America and the Caribbean.
 * Discogs' common, historical and regional names are aliases. In particular, Russia
 * follows M49's Europe assignment, while an USSR release remains International.
 */
const COUNTRIES: Record<Exclude<CrateContinent, 'unknown'>, readonly string[]> = {
  africa: [
    'Africa',
    'Algeria',
    'Angola',
    'Benin',
    'Botswana',
    'British Indian Ocean Territory',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cape Verde',
    'Cameroon',
    'Central African Republic',
    'Chad',
    'Comoros',
    'Congo',
    'Democratic Republic of the Congo',
    'Congo, Democratic Republic of the',
    'Congo, Republic of the',
    'Zaire',
    'Djibouti',
    'Egypt',
    'Equatorial Guinea',
    'Eritrea',
    'Eswatini',
    'Swaziland',
    'Ethiopia',
    'French Southern Territories',
    'Gabon',
    'Gambia',
    'Ghana',
    'Guinea',
    'Guinea-Bissau',
    'Côte d’Ivoire',
    "Côte d'Ivoire",
    'Ivory Coast',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libya',
    'Libyan Arab Jamahiriya',
    'Madagascar',
    'Malawi',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Morocco',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Réunion',
    'Rwanda',
    'Saint Helena',
    'Sao Tome and Principe',
    'Senegal',
    'Seychelles',
    'Sierra Leone',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Sudan',
    'Tanzania',
    'United Republic of Tanzania',
    'Togo',
    'Tunisia',
    'Uganda',
    'Western Sahara',
    'Zambia',
    'Zimbabwe',
    'Rhodesia',
  ],
  asia: [
    'Asia',
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bahrain',
    'Bangladesh',
    'Bhutan',
    'Brunei',
    'Brunei Darussalam',
    'Cambodia',
    'China',
    'Cyprus',
    'Georgia',
    'Hong Kong',
    'China, Hong Kong Special Administrative Region',
    'India',
    'Indonesia',
    'Iran',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Israel',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    "Lao People's Democratic Republic",
    'Lebanon',
    'Macao',
    'Macau',
    'China, Macao Special Administrative Region',
    'Malaysia',
    'Maldives',
    'Mongolia',
    'Myanmar',
    'Burma',
    'Nepal',
    'North Korea',
    "Democratic People's Republic of Korea",
    'Oman',
    'Pakistan',
    'Palestine',
    'State of Palestine',
    'Philippines',
    'Qatar',
    'Saudi Arabia',
    'Singapore',
    'South Korea',
    'Republic of Korea',
    'Sri Lanka',
    'Syria',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'East Timor',
    'Turkey',
    'Türkiye',
    'Turkmenistan',
    'United Arab Emirates',
    'Uzbekistan',
    'Vietnam',
    'Viet Nam',
    'Yemen',
  ],
  europe: [
    'Europe',
    'European Union',
    'EU',
    'Benelux',
    'Scandinavia',
    'Åland Islands',
    'Albania',
    'Andorra',
    'Austria',
    'Belarus',
    'Belgium',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Czechia',
    'Czech Republic',
    'Czechoslovakia',
    'Denmark',
    'Estonia',
    'Faroe Islands',
    'Finland',
    'France',
    'Germany',
    'German Democratic Republic (GDR)',
    'East Germany',
    'West Germany',
    'Gibraltar',
    'Greece',
    'Guernsey',
    'Holy See',
    'Vatican City',
    'Hungary',
    'Iceland',
    'Ireland',
    'Isle of Man',
    'Italy',
    'Jersey',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Republic of Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'Netherlands (Kingdom of the)',
    'North Macedonia',
    'Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Russian Federation',
    'San Marino',
    'Serbia',
    'Serbia and Montenegro',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Svalbard and Jan Mayen Islands',
    'Sweden',
    'Switzerland',
    'Ukraine',
    'United Kingdom',
    'UK',
    'United Kingdom of Great Britain and Northern Ireland',
    'Great Britain',
    'England',
    'Scotland',
    'Wales',
    'Northern Ireland',
    'Yugoslavia',
  ],
  northAmerica: [
    'North America',
    'Central America',
    'Caribbean',
    'Anguilla',
    'Antigua and Barbuda',
    'Aruba',
    'Bahamas',
    'Barbados',
    'Belize',
    'Bermuda',
    'Bonaire, Sint Eustatius and Saba',
    'British Virgin Islands',
    'Canada',
    'Cayman Islands',
    'Costa Rica',
    'Cuba',
    'Curaçao',
    'Dominica',
    'Dominican Republic',
    'El Salvador',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guatemala',
    'Haiti',
    'Honduras',
    'Jamaica',
    'Martinique',
    'Mexico',
    'Montserrat',
    'Netherlands Antilles',
    'Nicaragua',
    'Panama',
    'Puerto Rico',
    'Saint Barthélemy',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Martin (French Part)',
    'Saint Pierre and Miquelon',
    'Saint Vincent and the Grenadines',
    'Sint Maarten (Dutch part)',
    'Trinidad and Tobago',
    'Turks and Caicos Islands',
    'United States',
    'United States of America',
    'US',
    'USA',
    'United States Virgin Islands',
    'Virgin Islands',
  ],
  southAmerica: [
    'South America',
    'Argentina',
    'Bolivia',
    'Bolivia (Plurinational State of)',
    'Bouvet Island',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Falkland Islands',
    'Falkland Islands (Malvinas)',
    'French Guiana',
    'Guyana',
    'Paraguay',
    'Peru',
    'South Georgia and the South Sandwich Islands',
    'Suriname',
    'Uruguay',
    'Venezuela',
    'Venezuela (Bolivarian Republic of)',
  ],
  oceania: [
    'Oceania',
    'Australasia',
    'American Samoa',
    'Australia',
    'Christmas Island',
    'Cocos (Keeling) Islands',
    'Cook Islands',
    'Fiji',
    'French Polynesia',
    'Guam',
    'Heard Island and McDonald Islands',
    'Kiribati',
    'Marshall Islands',
    'Micronesia',
    'Micronesia (Federated States of)',
    'Nauru',
    'Naoero',
    'New Caledonia',
    'New Zealand',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands',
    'Palau',
    'Papua New Guinea',
    'Pitcairn',
    'Samoa',
    'Solomon Islands',
    'Tokelau',
    'Tonga',
    'Tuvalu',
    'United States Minor Outlying Islands',
    'Vanuatu',
    'Wallis and Futuna',
    'Wallis and Futuna Islands',
  ],
  antarctica: ['Antarctica'],
  international: ['Worldwide', 'World', 'International', 'USSR', 'Soviet Union', 'Latin America'],
};

const continentByCountry = new Map<string, CrateContinent>(
  Object.entries(COUNTRIES).flatMap(([continent, countries]) =>
    countries.flatMap((country) =>
      [country, country.replace(/\band\b/g, '&')].map(
        (alias) => [normalizeText(alias), continent as CrateContinent] as const,
      ),
    ),
  ),
);

/** A composite territory is only assigned when all of its components are understood. */
export function countryToContinent(country: string | null): CrateContinent {
  if (!country?.trim()) return 'unknown';
  // An unfinished composite must not become a known country when punctuation is removed.
  if (/^[,&/]|[,&/]$/.test(country.trim())) return 'unknown';
  const exact = continentByCountry.get(normalizeText(country));
  if (exact) return exact;

  const parts = country.split(/\s*(?:,|&|\/|\band\b)\s*/i).filter(Boolean);
  if (parts.length < 2) return 'unknown';
  const continents = parts.map((part) => continentByCountry.get(normalizeText(part)));
  if (continents.some((continent) => !continent)) return 'unknown';
  const distinct = new Set(continents);
  return distinct.size === 1 ? continents[0]! : 'international';
}
